require:
  # add after moving docs to another tool
  # - standard/cop/semantic_blocks
  - 'rubocop-md'

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'clowne.gemspec'
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Markdown:
  WarnInvalid: true

Lint/Void:
  Exclude:
    - 'README.md'
