require:
  # add after moving docs to another tool
  - 'standard/cop/block_single_line_braces'
  - 'rubocop-md'

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'clowne.gemspec'
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Markdown:
  WarnInvalid: true

Lint/Void:
  Exclude:
    - 'docs/README.md'
    - 'README.md'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'
