inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rspec.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*.rb
