require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'