AllCops:
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false
