inherit_gem:
  standard: config/base.yml

Lint/Void:
  Exclude:
    - '*.md'

Metrics/AbcSize:
  Enabled: false

Standard/SemanticBlocks:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
